### ISSUE TITLE
New Feature For Skipping Specified Char

### ISSUE THREAD

**Issue by nitishthakrarsa** [jonschlinkert/randomatic#12]
Recently I was working on one project and I was asked to generate a random String with numeric and letter values with specified number like 0 and specified char O as my client was getting confused in between this two char. 

So I am suggesting here to add one more argument to the function with array specified value like as below.
[ '0', 'O', 'o'] so it will generate a random string without given values in array.

**Comment by doowb** [comment]
I think this is a good idea, but it should be an option on the `options` object instead of another argument to the function. Would you like to do a PR?

**Comment by jonschlinkert** [comment]
what if we just allow a function to be passed, so you can dynamically choose the character to use?

**Comment by kivlor** [comment]
I've opened a PR (#16) that adds `exclude` to the options that will take a string or an array. I wasn't sure the best approach to take to allow passing a function... Sorry @jonschlinkert
