### ISSUE TITLE
NPM 6 vulnerability - Cryptographically Weak PRNG

### ISSUE THREAD

**Issue by yogenpatel** [jonschlinkert/randomatic#14]
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Cryptographically Weak PRNG                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ randomatic                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > jest-validate > jest-config >              │
│               │ jest-jasmine2 > jest-util > jest-message-util > micromatch > │
│               │ braces > expand-range > fill-range > randomatic              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/157                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by doowb** [comment]
#13
