### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by sangdth** [jonschlinkert/randomatic#24]
First of all, thank you for making such useful yet easy to use library. I like this library and use it whenever I can.

Lately I have some Typescript projects, which have problem with `import`, so for now I still mix import with require('randomatic'), just wonder is there any plan for supporting Typescript?

Regards.

**Comment by doowb** [comment]
A PR to add a TypeScript definitions file would be appreciated!

**Comment by sangdth** [comment]
I'm working on it. :D
