### ISSUE TITLE
Math.random() is not

### ISSUE THREAD

**Issue by tomByrer** [jonschlinkert/randomatic#4]
Shouldn't use built in JS Math.random() since it will repeat itself; too dangerous to use for 'Unique ID' etc.
https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.uskhjv9vc

Might be a while before I can even copy/paste & quick test a solution from there, let alone add the 'white noise' & other repeating tests.

tr;dr: "[use urandom](http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/). In browser you can use [crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues)"  I'm not sure if V8's `crypto.getRandomValues()` can be exposed in node; seems to have its own crypto lib.  But node does have [crypto.randomBytes(size[, callback])](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback)

**Comment by ronkorving** [comment]
I would love to see `crypto.randomBytes` being used, it's the only thing keeping me from loving this library and using it today.

**Comment by jonschlinkert** [comment]
I'd like to see it implemented as well, I'd take a pr if someone wants to give it a go.

**Comment by tomByrer** [comment]
Nice wrapper, but should we worry about in-browser usage @jonschlinkert ?
https://github.com/crypto-utils/random-bytes

**Comment by jonschlinkert** [comment]
We should try to address it at least. I think there is a browserify plugin for crypto, but I haven't looked at it, no idea if it's a viable solution for this. that does look like a nice wrapper

**Comment by jonschlinkert** [comment]
btw, if someone wants to propose a PR I'd be happy to consider one. Please start with an issue to discuss the algorithm, thanks!
