### ISSUE TITLE
TypeError: Map constructor does not accept arguments

### ISSUE THREAD

**Issue by X-Tender** [jonschlinkert/randomatic#5]
I get this error when I try to run it in IOS 8 - Safari
I didnt use it directly, I use react with some modules and honestly I dont know here it comes from. I only identifyed it in your module from the error Message.

**Comment by jonschlinkert** [comment]
`Map` is not used here. Sounds like the error caused by/in another module.

**Comment by X-Tender** [comment]
Ok. Sorry for bothering you :)
